export const medicalEquipmentList = [
  {
    label: "LABORATOIRE D'ANALYSES MÉDICALES",
    options: [
      "Automates d'hématologie (SYSMEX XQ-320, XN-Series, Mindray BC-Series)",
      "Coagulomètres (Stago, Diagnostica)",
      "Agrégomètres plaquettaires",
      "Lecteurs de vitesse de sédimentation (VES)",
      "Centrifugeuses (micro-hématocrite, standard)",
      "Agitateurs de tubes",
      "Colorateurs de lames (RAL Stainer, HemaTek)",
      "Automates de biochimie (Cobas C111, C311, C501, Architect)",
      "Spectrophotomètres",
      "Analyseurs d'électrolytes (ISE)",
      "Analyseurs de gaz du sang",
      "Glucomètres de laboratoire",
      "Photomètres de flamme",
      "Osmomètres",
      "Automates d'immunoanalyse (Mini VIDAS, VIDAS, Architect i1000)",
      "Lecteurs ELISA",
      "Laveurs de microplaques",
      "Incubateurs de microplaques",
      "Agitateurs de microplaques",
      "Néphélomètres",
      "Analyseurs d'électrophorèse",
      "Incubateurs bactériologiques (35°C, 42°C)",
      "Étuves de stérilisation",
      "Autoclaves",
      "Hottes à flux laminaire (PSM)",
      "Spectromètres de masse (MALDI-TOF)",
      "Automates d'hémoculture (BacT/Alert, BACTEC)",
      "Automates d'identification et antibiogramme (VITEK, Phoenix)",
      "Microscopes (optiques, fluorescence)",
      "Réfrigérateurs médicaux (2-8°C)",
      "Congélateurs (-20°C, -80°C)",
      "Bains-marie",
      "Balances de précision",
      "pH-mètres",
      "Pipettes automatiques",
      "Distributeurs/diluteurs automatiques",
      "Agitateurs magnétiques",
      "Vortex",
      "Système de production d'eau pure (osmoseur, déioniseur)",
    ],
  },
  {
    label: "IMAGERIE MÉDICALE",
    options: [
      "Appareils de radiographie fixe",
      "Appareils de radiographie mobile",
      "Amplificateurs de brillance (scopie)",
      "Tables télécommandées",
      "Développeuses automatiques (systèmes analogiques)",
      "Reprographes laser (CR)",
      "Stations de travail PACS",
      "Négatoscopes",
      "Échographes fixes (multi-sondes)",
      "Échographes portables",
      "Sondes d'échographie (linéaire, convexe, endocavitaire, cardiaque)",
      "Imprimantes thermiques pour échographie",
      "Systèmes Doppler",
      "Tomodensitomètres (Scanner)",
      "IRM",
      "Injecteurs automatiques de produit de contraste",
      "Stations de reconstruction 3D",
      "Mammographes",
      "Panoramiques dentaires",
      "Ostéodensitomètres (DEXA)",
    ],
  },
  {
    label: "BLOC OPÉRATOIRE",
    options: [
      "Ventilateurs d'anesthésie",
      "Moniteurs multiparamétriques (ECG, SpO2, PNI, T°, capnographie)",
      "Défibrillateurs",
      "Pousse-seringues électriques",
      "Pompes à perfusion volumétriques",
      "Réchauffeurs de fluides",
      "Matelas chauffants",
      "Aspirateurs chirurgicaux",
      "Analyseurs de gaz anesthésiques",
      "Tables d'opération (électriques, hydrauliques)",
      "Éclairages opératoires (scialytiques)",
      "Bras de suspension (plafonniers)",
      "Bistouris électriques (monopolaire, bipolaire)",
      "Lasers chirurgicaux (CO2, YAG)",
      "Microscopes opératoires",
      "Colonnes de cœlioscopie",
      "Insufflateurs de CO2",
      "Sources de lumière froide",
      "Caméras endoscopiques",
      "Moteurs chirurgicaux (orthopédie, neurochirurgie)",
      "Systèmes de navigation chirurgicale",
      "Autoclaves à vapeur (134°C, 121°C)",
      "Stérilisateurs basse température (plasma, formaldéhyde)",
      "Laveurs-désinfecteurs",
      "Soudeuses de sachets",
      "Incubateurs biologiques (test de stérilité)",
    ],
  },
  {
    label: "URGENCES ET RÉANIMATION",
    options: [
      "Ventilateurs de réanimation",
      "Respirateurs de transport",
      "CPAP/BiPAP",
      "Moniteurs de surveillance (multiparamétriques)",
      "Centrales de surveillance",
      "Défibrillateurs avec stimulateur externe",
      "Électrocardiographes (12 dérivations)",
      "Pousse-seringues et pompes à perfusion",
      "Réchauffeurs de patients",
      "Appareils d'assistance circulatoire (ECMO, ballon de contre-pulsion)",
      "Hémodialyseurs (épuration extra-rénale)",
      "Échographes d'urgence (FAST)",
    ],
  },
  {
    label: "MATERNITÉ ET NÉONATOLOGIE",
    options: [
      "Cardiotocographes (monitoring fœtal)",
      "Échographes obstétricaux",
      "Tables d'accouchement",
      "Aspirateurs de mucosités",
      "Doppler fœtaux",
      "Couveuses (incubateurs fermés)",
      "Tables de réanimation néonatale",
      "Berceaux chauffants (radiants)",
      "Photothérapie (conventionnelle, intensive)",
      "Ventilateurs néonataux",
      "CPAP néonatale",
      "Moniteurs multiparamétriques néonataux",
      "Pousse-seringues de précision",
      "Bilirubinomètres transcutanés",
    ],
  },
  {
    label: "CONSULTATIONS ET HOSPITALISATION",
    options: [
      "Tensiomètres automatiques",
      "Thermomètres électroniques",
      "Oxymètres de pouls",
      "Pèse-personnes et pèse-bébés électroniques",
      "Toises électroniques",
      "Glucomètres capillaires",
      "Spiromètres",
      "Peak-flow mètres",
      "ECG portables",
      "Holters ECG et tensionnels",
      "Lits médicalisés électriques",
      "Pompes à nutrition entérale",
      "Aspirateurs de mucosités mobiles",
      "Nébuliseurs/aérosols",
      "Compresseurs médicaux portables",
      "Concentrateurs d'oxygène",
      "Moniteurs de surveillance simples",
    ],
  },
  {
    label: "SPÉCIALITÉS",
    options: [
      "Biomicroscopes (lampes à fente)",
      "Tonomètres (aplanation, air pulsé)",
      "Réfractomètres automatiques",
      "Kératomètres",
      "Périmètres (champ visuel)",
      "Rétinographes",
      "OCT (tomographie en cohérence optique)",
      "Lasers ophtalmologiques (YAG, Argon)",
      "Phacoémulsificateurs",
      "Microscopes ORL",
      "Endoscopes rigides et flexibles",
      "Tours d'endoscopie",
      "Audiomètres",
      "Tympanomètres",
      "Vidéonystagmographes",
      "Unités ORL complètes",
      "Échocardiographes cardiaques",
      "Systèmes d'épreuve d'effort",
      "Holters ECG",
      "MAPA (Holter tensionnel)",
      "Polygraphes ventilatoires",
      "Units dentaires",
      "Radiographie dentaire intra-orale",
      "Compresseurs dentaires",
      "Autoclaves classe B",
      "Détartreurs ultrasoniques",
      "Lampes de photopolymérisation",
      "Appareils d'électrothérapie",
      "Ultrasons thérapeutiques",
      "Ondes de choc",
      "Lasers thérapeutiques",
      "Appareils de pressothérapie",
      "Tables de verticalisation",
      "Appareils d'isocinétisme",
    ],
  },
  {
    label: "SUPPORT ET INFRASTRUCTURE",
    options: [
      "Centrales d'oxygène (concentrateurs PSA)",
      "Centrales de vide",
      "Centrales d'air médical",
      "Compresseurs médicaux (centrale)",
      "Surpresseurs",
      "Groupes électrogènes",
      "Onduleurs (UPS)",
      "Régulateurs de tension",
      "Réfrigérateurs pour médicaments",
      "Réfrigérateurs pour vaccins",
      "Congélateurs pour plasma",
      "Chambres froides",
      "Enregistreurs de température",
    ],
  },
];