export const locations = [
  {
    label: "Zones Générales",
    options: [
      "Parking",
      "Accueil",
      "Extérieur",
    ],
  },
  {
    label: "Consultations",
    options: [
      "Salle de consultation Ntoum",
      "Salle de consultation Okondja",
      "Salle de consultation Ndendé",
      "Salle de consultation Fougamou",
      "Salle de consultation Port-Gentil",
      "Salle de consultation Lambaréné",
    ],
  },
  {
    label: "Rez-de-chaussée : Urgences",
    options: [
      "Salle de permanence médecins",
      "Box 1",
      "Box 2",
      "Box 3",
      "Salle de déchocage",
      "Bureau des urgences",
      "Petite infirmerie",
      "Salle de vestiaire (Urgences)",
      "Salle de soins intensifs",
      "Salle d'hospitalisation Addis abeba",
      "Bureau de consultation Johannesburg",
      "Bureau de consultation Mayumba",
      "Bureau de consultation Gambas",
      "Bureau de consultation Lekoni",
      "Salle de prélèvement (Urgences)",
      "Salle de prise de paramètres",
      "Bureau kango",
      "Espace d'attente 1 (Urgences)",
      "Espace d'attente 2 (Urgences)",
      "Salle de pharmacie urgence",
    ],
  },
  {
    label: "Rez-de-chaussée : Autres",
    options: [
      "WC non utilisable",
      "Stock pour les agents d'entretien",
      "Bureau consultation koulamoutou",
      "Salle consultation mouila",
      "Toilettes (RDC)",
    ],
  },
  {
    label: "Pôle G2 (Médecine externe)",
    options: [
      "Salle d'attente G2",
      "Bureau de consultation Lastourville",
      "Bureau de consultation Lambaréné",
      "Bureau de consultation Port-Gentil",
      "Bureau de consultation Makokou",
    ],
  },
  {
    label: "Pôle G3 (Laboratoire)",
    options: [
      "Salle d'attente G3",
      "Salle de prélèvement 1",
      "Salle de prélèvement 2",
      "Salle de prélèvement 3",
      "Salle de prélèvement 4 (non fonctionnelle)",
      "Salle de prélèvement 5 (non fonctionnelle)",
      "Laboratoire - Bureau",
      "Laboratoire - Salle administratif",
      "Laboratoire - Salle de biochimie",
      "Laboratoire - Salle de sérologie/immunologie",
      "Laboratoire - Salle d'hématologie/bactériologie",
      "Laboratoire - Salle de trie",
      "Laboratoire - Salle de permanence",
      "Laboratoire - WC",
      "Laboratoire - Salle d'anapath (hors fonction)",
    ],
  },
  {
    label: "Hospitalisations du 1er étage",
    options: [
      "Salle d'infirmerie (1er étage)",
      "Toilettes (1er étage)",
      "Chambre Woleu",
      "Chambre Ntem",
      "Chambre Mpassa",
      "Chambre Lolo",
      "Chambre Ngounié",
      "Espace service de maternité et blocs",
    ],
  },
  {
    label: "Hospitalisations du 2e étage",
    options: [
      "Salle d'infirmerie (2e étage)",
      "Chambre Ogooué",
      "Chambre Komo",
      "Chambre Nyanga",
      "Chambre Ivindo",
      "Chambre Abanga",
      "Chambre Mbei",
      "Salle de Méo",
      "WC (2e étage)",
      "Salle d'échange pour le personnel",
    ],
  },
  {
    label: "Spécialités du 2e étage",
    options: [
      "Salle d'attente Spécialités 1",
      "Salle d'attente Spécialités 2",
      "Bureau de consultation Okondjo",
      "Bureau de consultation Ndendé",
      "Bureau de consultation Mbigou",
      "Bureau de consultation Gynéco/Pédiatrie",
      "Bureau de consultation Spécialités 1",
      "Bureau de consultation Spécialités 2",
      "Bureau de consultation Spécialités 3",
      "Salle de paramètres (Spécialités)",
      "Salle de paramètres (VAM)",
      "Salle de vestiaire et box d'échange (Pédiatrie)",
    ],
  },
  {
    label: "Administration",
    options: [
      "2e étage - Cotation",
      "2e étage - Comptabilité",
      "2e étage - Cuisine",
      "2e étage - ITI",
      "2e étage - Stock",
      "3e étage - Direction Générale",
    ],
  },
];