INSERT INTO public.rooms (id, name, capacity, location, doctor_in_charge)
VALUES
    (gen_random_uuid(), 'Salle de consultation Akanda', 2, 'Rez-de-chaussée : Imagerie médicale', NULL),
    (gen_random_uuid(), 'Box 1 (Urgences)', 1, 'Rez-de-chaussée : Urgences', NULL),
    (gen_random_uuid(), 'Box 2 (Urgences)', 1, 'Rez-de-chaussée : Urgences', NULL),
    (gen_random_uuid(), 'Box 3 (Urgences)', 1, 'Rez-de-chaussée : Urgences', NULL),
    (gen_random_uuid(), 'Salle de déchocage', 3, 'Rez-de-chaussée : Urgences', NULL),
    (gen_random_uuid(), 'Bureau de consultation Johannesburg', 2, 'Rez-de-chaussée : Urgences', NULL),
    (gen_random_uuid(), 'Bureau de consultation Mayumba', 2, 'Rez-de-chaussée : Urgences', NULL),
    (gen_random_uuid(), 'Bureau de consultation Gambas', 2, 'Rez-de-chaussée : Urgences', NULL),
    (gen_random_uuid(), 'Bureau de consultation Lekoni', 2, 'Rez-de-chaussée : Urgences', NULL),
    (gen_random_uuid(), 'Bureau consultation Koulamoutou', 2, 'Rez-de-chaussée : Autres', NULL),
    (gen_random_uuid(), 'Salle consultation Mouila', 2, 'Rez-de-chaussée : Autres', NULL),
    (gen_random_uuid(), 'Salle d''attente G2', 10, 'Pôle G2 (Médecine externe)', NULL),
    (gen_random_uuid(), 'Bureau de consultation Lastourville', 2, 'Pôle G2 (Médecine externe)', NULL),
    (gen_random_uuid(), 'Bureau de consultation Lambaréné', 2, 'Pôle G2 (Médecine externe)', NULL),
    (gen_random_uuid(), 'Bureau de consultation Port-Gentil', 2, 'Pôle G2 (Médecine externe)', NULL),
    (gen_random_uuid(), 'Bureau de consultation Makokou', 2, 'Pôle G2 (Médecine externe)', NULL),
    (gen_random_uuid(), 'Salle d''infirmerie (1er étage)', 1, 'Hospitalisations du 1er étage', NULL),
    (gen_random_uuid(), 'Chambre Woleu', 1, 'Hospitalisations du 1er étage', NULL),
    (gen_random_uuid(), 'Chambre Ntem', 1, 'Hospitalisations du 1er étage', NULL),
    (gen_random_uuid(), 'Chambre Mpassa', 1, 'Hospitalisations du 1er étage', NULL),
    (gen_random_uuid(), 'Chambre Lolo', 1, 'Hospitalisations du 1er étage', NULL),
    (gen_random_uuid(), 'Chambre Ngounié', 1, 'Hospitalisations du 1er étage', NULL),
    (gen_random_uuid(), 'Salle d''infirmerie (2e étage)', 1, 'Hospitalisations du 2e étage', NULL),
    (gen_random_uuid(), 'Chambre Ogooué', 1, 'Hospitalisations du 2e étage', NULL),
    (gen_random_uuid(), 'Chambre Komo', 1, 'Hospitalisations du 2e étage', NULL),
    (gen_random_uuid(), 'Chambre Nyanga', 1, 'Hospitalisations du 2e étage', NULL),
    (gen_random_uuid(), 'Chambre Ivindo', 1, 'Hospitalisations du 2e étage', NULL),
    (gen_random_uuid(), 'Chambre Abanga', 1, 'Hospitalisations du 2e étage', NULL),
    (gen_random_uuid(), 'Chambre Mbei', 1, 'Hospitalisations du 2e étage', NULL),
    (gen_random_uuid(), 'Salle de Méo', 1, 'Hospitalisations du 2e étage', NULL),
    (gen_random_uuid(), 'Bureau de consultation Okondjo', 2, 'Spécialités du 2e étage', NULL),
    (gen_random_uuid(), 'Bureau de consultation Ndendé', 2, 'Spécialités du 2e étage', NULL),
    (gen_random_uuid(), 'Bureau de consultation Mbigou', 2, 'Spécialités du 2e étage', NULL),
    (gen_random_uuid(), 'Bureau de consultation Gynéco/Pédiatrie', 2, 'Spécialités du 2e étage', NULL),
    (gen_random_uuid(), 'Bureau de consultation Spécialités 1', 2, 'Spécialités du 2e étage', NULL),
    (gen_random_uuid(), 'Bureau de consultation Spécialités 2', 2, 'Spécialités du 2e étage', NULL),
    (gen_random_uuid(), 'Bureau de consultation Spécialités 3', 2, 'Spécialités du 2e étage', NULL);