// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gjjjnltiwplzzgovusvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqampubHRpd3Bsenpnb3Z1c3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTIzNjUsImV4cCI6MjA2ODkyODM2NX0.YJwt4Exc8IB8UCa-0lI1oVjXW5G4wAT3Y0azFsbTKlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);